### ISSUE TITLE
Change resolution

### ISSUE THREAD

**Issue by NickNes9** [Helco/ZZSpeeds#6]
Hello, your program works great but it would be amazing if you would include more resolutions to it.
This python code patches zanthp.exe to work in any resolution (indicated by REX_X,RES_Y line), but I couldn't make it work alongside your .exe.
Thank you.

`#!/usr/bin/python
from struct import pack, unpack

RES_X,RES_Y = 1920,1080
resX = pack("<L", RES_X).encode("hex")
resY = pack("<L", RES_Y).encode("hex")
ratios,offsets = [round(640/480.0, 2), round(1920/1080.0, 2), round(1920/1200.0, 2)],[0, 0.25, 0.17]
r = offsets[ratios.index(round(RES_X/float(RES_Y), 2))]

p1 = [0x001078, "9090"]
p2 = [0x01128c, "e90e2c1900"]
p3 = [0x0f5c43, "59595968"+resY+"68"+resX+"5233c9894c2414894c2410b820000000"]
p4 = [0x1a3e9f, "8d732c8bcec7442408"+resX+"c744240c"+resY+"e9d8d3e6ff"]
p5 = [0x1a5fcc, pack("<f", RES_Y/float(RES_X)).encode("hex")]
p6 = [0x1a6508, pack("<f", RES_Y/float(RES_X)).encode("hex")]
p7 = [0x019430, "e987aa1800" + "90"*26]
p8 = [0x1a3ebc, "c74108"+resX+"c7410c"+resY+"c7411020000000c74114000000005ec20400"]
skills,icon,gauge,bars = [0x1a60ac],[0x1a7278, 0x1a727c],[0x1a7290, 0x1a7294],[0x1a6e6c, 0x1a72ac]

with open("zanthp.exe", "rb") as f: blob = f.read()
for p in [p1, p2, p3, p4, p5, p6, p7, p8]: blob = blob[:p[0]] + p[1].decode("hex") + blob[p[0]+len(p[1].decode("hex")):]
for i in (skills+icon+gauge+bars):
    t = unpack("<f", blob[i:i+4])[0]
    blob = blob[:i] + pack("<f", t-t*r) + blob[i+4:]
with open("zanthp."+str(RES_X)+"x"+str(RES_Y)+".exe", "wb") as f: f.write(blob)`

**Comment by NickNes9** [comment]
Did a bit more testing, managed to run the patched EXE with your launcher (since it's just looking for 'zanthp.exe'), however the launcher stays small and only shows the top left corner of the game.
The fix might be simple if you would just add new resolutions to the launcher window.

**Comment by Helco** [comment]
I think I have a fix for you: https://github.com/Helco/ZZSpeeds/releases/tag/1.6
A couple of notes about that patch:
- You will still have to rename the patched exe to 'zanthp.exe'
- There might be short lags when opening menus - this is related to the high resolution and sadly infeasible to fix
- In the main menus there are graphical glitches caused by the widescreen mode
- Optionally I would recommend to remove the `p6` from line 21 in the patch as that is related to footstep volume instead of any screen ratio (afaik)

If you have any problems with it, feel free to reopen this issue.
